In [5]:
import pandas as pd

In [6]:
data = pd.read_csv('data_movies.csv')
data.head(1)

   movie_id   title                                               info
0     19995  avatar  action adventure fantasy sciencefiction cultur...

In [7]:
data['info'][0]

'action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. ingeniousfilmpartners twentiethcenturyfoxfilmcorporation duneentertainment lightstormentertainment avatar samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez jamescameron jamescameron'

In [8]:
# So as you can see alot of words are from same root, so its better for us to replace them with same words because e.g love,loved, loving have same root word
# lov but if we keep all love loved loving model will consider them as separate word but we want them as same so our model learns that they are similar
# kinda movies

In [9]:
import nltk

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
cv =  CountVectorizer(max_features = 7000, stop_words = "english")

In [12]:
vectors = cv.fit_transform(data['info']).toarray()

In [13]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 7000))

In [14]:
cv.get_feature_names_out()[0:70]

array(['000', '007', '10', '100', '10th', '11', '12', '13', '13th', '14',
       '1492pictures', '15', '150', '16', '17', '17th', '18', '18th',
       '18thcentury', '19', '1930s', '1940s', '1941', '1944', '1950',
       '1950s', '1955', '1959', '1960', '1960s', '1962', '1964', '1965',
       '1967', '1970s', '1971', '1972', '1973', '1974', '1976', '1979',
       '1980', '1980s', '1984', '1985', '1990s', '1995', '1997', '1999',
       '19th', '19thcentury', '20', '200', '2000', '2001', '2003', '2009',
       '20th', '21', '21lapsentertainment', '21st', '23', '24', '25',
       '27', '28', '2929productions', '30', '300', '3artsentertainment'],
      dtype=object)

In [15]:
from nltk.stem.porter import PorterStemmer

In [16]:
ps = PorterStemmer()

In [17]:
def rootWords(str):
    x = []
    for i in str.split():
        x.append(ps.stem(i))

    return " ".join(x)

In [18]:
rootWords('loved')

'love'

In [19]:
data['info'].apply(rootWords)

0       action adventur fantasi sciencefict culturecla...
1       adventur fantasi action ocean drugabus exotici...
2       action adventur crime spi basedonnovel secreta...
3       action crime drama thriller dccomic crimefight...
4       action adventur sciencefict basedonnovel mar m...
                              ...
4801    action crime thriller unitedstates–mexicobarri...
4802    comedi romanc a newlyw couple' honeymoon is up...
4803    comedi drama romanc tvmovi date loveatfirstsig...
4804    when ambiti new york attorney sam is sent to s...
4805    documentari obsess camcord crush dreamgirl eve...
Name: info, Length: 4806, dtype: object

In [20]:
data['info'] = data['info'].apply(rootWords)
data['info'][0]

'action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. ingeniousfilmpartn twentiethcenturyfoxfilmcorpor duneentertain lightstormentertain avatar samworthington zoesaldana sigourneyweav stephenlang michellerodriguez jamescameron jamescameron'

In [21]:
cv2 = CountVectorizer(max_features = 7000 ,stop_words = "english")

In [22]:
vectors = cv2.fit_transform(data['info']).toarray()

In [23]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 7000))

In [24]:
cv2.get_feature_names_out()[0:500]

array(['000', '007', '10', '100', '10th', '11', '12', '13', '13th', '14',
       '1492pictur', '15', '150', '16', '17', '17th', '18', '1890',
       '18th', '18thcenturi', '19', '1910', '1920', '1930', '1940',
       '1941', '1944', '1950', '1950s', '1955', '1959', '1960', '1960s',
       '1962', '1964', '1965', '1967', '1970', '1970s', '1971', '1972',
       '1973', '1974', '1976', '1979', '1980', '1980s', '1984', '1985',
       '1990', '1995', '1997', '1999', '19th', '19thcenturi', '20', '200',
       '2000', '2001', '2003', '2009', '20th', '21', '21lapsentertain',
       '21st', '23', '24', '25', '27', '28', '2929product', '30', '300',
       '3artsentertain', '3d', '40', '40acres', '47', '50', '500', '51',
       '60', '60s', '70', '80', 'a24', 'aaron', 'aaroneckhart',
       'aaronseltz', 'aarontaylor', 'abandapart', 'abandon', 'abbi',
       'abbiecornish', 'abduct', 'abigailbreslin', 'abil', 'abl',
       'aboard', 'aborigin', 'abov', 'abram', 'abroad', 'absolut',
       'absurd', 'abus', 'academ', 'academi', 'academy', 'accept',
       'access', 'accid', 'accident', 'acclaim', 'accompani',
       'accomplish', 'account', 'accus', 'ace', 'achiev', 'acquaint',
       'acquir', 'act', 'action', 'actionhero', 'activ', 'activist',
       'activities', 'actor', 'actress', 'actual', 'ad', 'adam',
       'adambrodi', 'adamgoldberg', 'adammckay', 'adamsandl', 'adamscott',
       'adamshankman', 'adapt', 'add', 'addict', 'adjust', 'admir',
       'admit', 'adolesc', 'adopt', 'ador', 'adrienbrodi', 'adrift',
       'adult', 'adultanim', 'adulteri', 'adulthood', 'adults', 'advanc',
       'advantag', 'adventur', 'adventure', 'adventures', 'advertis',
       'advic', 'advis', 'affair', 'affc', 'affect', 'affirmfilm',
       'affluent', 'afghanistan', 'afraid', 'africa', 'african',
       'africanamerican', 'aftercreditssting', 'afterlif', 'aftermath',
       'ag', 'age', 'agediffer', 'agenc', 'agency', 'agenda', 'agent',
       'agents', 'aggress', 'ago', 'agre', 'ahead', 'aid', 'aidanquinn',
       'ail', 'aim', 'air', 'airborn', 'aircraft', 'airplan',
       'airplanecrash', 'airport', 'aka', 'al', 'alabama', 'alan',
       'alanalda', 'alanarkin', 'alanrickman', 'alantudyk', 'alaska',
       'albert', 'albertbrook', 'alcatraz', 'alcohol', 'alcoholabus',
       'alconentertain', 'alecbaldwin', 'alecguin', 'alejandroamenábar',
       'alejandrogonzáleziñárritu', 'alessandronivola', 'alex',
       'alexanderpayn', 'alexanderskarsgård', 'alexandreaja',
       'alexapenavega', 'alexisbledel', 'alexkendrick', 'alexpettyf',
       'alfi', 'alfonsocuarón', 'alfredhitchcock', 'alfredmolina',
       'alfrewoodard', 'algeria', 'ali', 'alic', 'alice', 'alicebraga',
       'aliciasilverston', 'aliciavikand', 'aliciawitt', 'alien',
       'alieninvas', 'alienlife', 'alienplanet', 'aliens', 'alik',
       'alilart', 'aliv', 'alive', 'alleg', 'allen', 'alli', 'allianc',
       'allianceatlantiscommun', 'alliancefilm', 'allies',
       'allisonjanney', 'allow', 'alon', 'alongsid', 'alpacino', 'alpha',
       'alphavillefilm', 'alreadi', 'alter', 'altern', 'alvin', 'alway',
       'alysonhannigan', 'alyssa', 'alzheimer', 'amanda', 'amandapeet',
       'amandaseyfri', 'amateur', 'amaz', 'amazon', 'ambassador',
       'amberheard', 'ambervalletta', 'ambit', 'ambiti',
       'amblinentertain', 'ambul', 'ambush', 'america', 'americaferrera',
       'american', 'americanabroad', 'americancivilwar',
       'americanfootbal', 'americanfootballplay', 'americanzoetrop',
       'ami', 'amid', 'amidst', 'amnesia', 'amp', 'amsterdam',
       'amulefilmwork', 'amus', 'amusementpark', 'amy', 'amyadam',
       'amypoehl', 'amyryan', 'amysmart', 'ana', 'anakin', 'analyst',
       'anarchiccomedi', 'ancient', 'ancientgreec', 'ancientrom',
       'ancientworld', 'anderson', 'andi', 'andiemacdowel', 'andrew',
       'andrewgarfield', 'andrewniccol', 'android', 'andy', 'andyfickman',
       'andygarcía', 'andysamberg', 'andyserki', 'andytenn', 'angel',
       'angela', 'angelabassett', 'angeles', 'angelinajoli', 'angelo',
       'anger', 'angle', 'angri', 'ani', 'anim', 'animalattack',
       'animalhorror', 'animals', 'anjelicahuston', 'ann', 'anna',
       'annabel', 'annafari', 'annakendrick', 'annapaquin',
       'annapurnapictur', 'annasophiarobb', 'anne', 'annebancroft',
       'annehathaway', 'annehech', 'annemoss', 'annetteben', 'anni',
       'annie', 'anniversari', 'announc', 'annual', 'anonym',
       'anonymouscont', 'anoth', 'answer', 'ant', 'antarct', 'antarctica',
       'antholog', 'anthoni', 'anthonyanderson', 'anthonyhopkin',
       'anthonymacki', 'anthropomorph', 'anti', 'antic', 'antihero',
       'antiqu', 'antoinefuqua', 'antoncapitalentertainment',
       'antoniobandera', 'antonyelchin', 'anyon', 'anyth', 'apart',
       'apartheid', 'apartment', 'apatowproduct', 'ape', 'apes',
       'apocalyps', 'apocalypse', 'apocalypt', 'apollo', 'appar',
       'appear', 'appianway', 'appl', 'apple', 'appli', 'appoint',
       'appreci', 'apprehend', 'apprentic', 'approach', 'approaches',
       'april', 'aquarium', 'arab', 'arbitrarylaw', 'arch',
       'archaeologist', 'archeolog', 'archer', 'architect', 'arctic',
       'area', 'aren', 'arena', 'argument', 'aris', 'aristocrat',
       'arizona', 'arm', 'armageddon', 'armandassant', 'armi',
       'armiehamm', 'arminmueller', 'armor', 'armsdeal', 'army', 'arnold',
       'arnoldschwarzenegg', 'arrang', 'arrangedmarriag', 'array',
       'arrest', 'arrested', 'arriv', 'arrives', 'arrog', 'arson', 'art',
       'artgalleri', 'arthur', 'articl', 'artifact', 'artifici',
       'artificialintellig', 'artisanentertain', 'artist', 'artists',
       'artlinsonproduct', 'artscouncilofengland', 'ash', 'ashley',
       'ashleyjudd', 'ashtonkutch', 'asia', 'asian', 'asid', 'ask',
       'aspect', 'aspir', 'ass', 'assassin', 'assault', 'assembl',
       'assign', 'assignment', 'assist', 'assistant', 'associ', 'assum',
       'asteroid', 'astralmedia', 'astronaut', 'asylum', 'atheist',
       'athlet', 'atlant', 'atlanta', 'atlasentertain',
       'atmosphereentertainmentmm', 'atom', 'atomegoyan', 'atomicbomb',
       'attach', 'attack', 'attacks', 'attempt', 'attemptedmurd',
       'attempttoescap', 'attend', 'attent', 'attic', 'attitud',
       'attorney', 'attract'], dtype=object)

In [25]:
# Now we need to calculate similarities

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

In [27]:
cosine_similarity(vectors).shape

(4806, 4806)

In [28]:
cosine_similarity(vectors)

array([[1.        , 0.06388766, 0.07045671, ..., 0.03818018, 0.        ,
        0.        ],
       [0.06388766, 1.        , 0.04901431, ..., 0.03984095, 0.01992048,
        0.0204765 ],
       [0.07045671, 0.04901431, 1.        , ..., 0.02196874, 0.        ,
        0.        ],
       ...,
       [0.03818018, 0.03984095, 0.02196874, ..., 1.        , 0.03571429,
        0.05506673],
       [0.        , 0.01992048, 0.        , ..., 0.03571429, 1.        ,
        0.07342231],
       [0.        , 0.0204765 , 0.        , ..., 0.05506673, 0.07342231,
        1.        ]], shape=(4806, 4806))

In [29]:
similarities = cosine_similarity(vectors)

In [30]:
sorted(list(enumerate(similarities[0])),reverse = True, key = lambda x: x[1])[1:8]

[(2405, np.float64(0.30544141932848495)),
 (1214, np.float64(0.2755939591076966)),
 (539, np.float64(0.23174488732966075)),
 (507, np.float64(0.2268861109474239)),
 (778, np.float64(0.2250967420452386)),
 (3728, np.float64(0.2132007163556104)),
 (1202, np.float64(0.2063386802081354))]

In [31]:
def recommend(movie):
    movie_index = data[data['title'] == movie.lower()].index[0]
    similarity = similarities[movie_index]
    movies_list = sorted(list(enumerate(similarity)), reverse=True, key=lambda x: x[1])[1:8]
    for i in movies_list:
        print(data.iloc[i[0]].title.title())

In [32]:
data.head(1)

   movie_id   title                                               info
0     19995  avatar  action adventur fantasi sciencefict culturecla...

In [33]:
recommend('Avatar')

Aliens
Aliens Vs Predator: Requiem
Titan A.E.
Independence Day
Meet Dave
Falcon Rising
Predators

In [34]:
recommend('Batman')

Batman
Batman & Robin
Batman Returns
Batman Begins
The Dark Knight
The Dark Knight Rises
Batman Forever

In [35]:
recommend('titanic')

Ghost Ship
Raise The Titanic
The Notebook
The Bounty
Under The Same Moon
The Chambermaid On The Titanic
Master And Commander: The Far Side Of The World

In [36]:
import pickle

In [37]:
pickle.dump(similarities,open('similarity.pkl','wb'))

In [38]:
with open('vectors.pkl', 'wb') as file:
    pickle.dump(vectors, file)

In [40]:
import pickle
import numpy as np

vectors = np.asarray(vectors, dtype=np.float32)

np.savez_compressed("vectors.npz", vectors=vectors)